const STATUS_PENDING = 0;
const STATUS_WAITING = 1;
const STATUS_SUCCESS = 2;

const ORDER_STATUS_ENUM = {
  STATUS_PENDING: "pending",
  STATUS_WAITING: "waiting",
  STATUS_SUCCESS: "success",
};

export default {
  STATUS_PENDING,
  STATUS_WAITING,
  STATUS_SUCCESS,
  ORDER_STATUS_ENUM,
};
