const STATUS_CREATE = 0;
const STATUS_WAITING = 1;
const STATUS_SUCCESS = 2;

const ORDER_STATUS_ENUM = {
	STATUS_CREATE: 'created',
	STATUS_WAITING: 'waiting',
	STATUS_SUCCESS: 'success',
};

export default {
	STATUS_CREATE,
	STATUS_WAITING,
	STATUS_SUCCESS,
	ORDER_STATUS_ENUM,
};
