const STATUS_ACTIVE = 1;
const STATUS_CREATE = 0;
const STATUS_INACTIVE = -1;

const PRODUCT_STATUS_ENUM = {
  STATUS_INACTIVE: "INACTIVE",
  STATUS_ACTIVE: "ACTIVE",
  STATUS_CREATE: "CREATE",
};

export default {
  STATUS_INACTIVE,
  STATUS_ACTIVE,
  STATUS_CREATE,
  PRODUCT_STATUS_ENUM,
};
