const STATUS_INACTIVE = 0;
const STATUS_CREATE = 1;
const STATUS_ACTIVE = 2;

const ROLE_USER_ADMIN = 1;
const ROLE_USER_SUPER_ADMIN = 2;

const USER_STATUS_NAME = {
	STATUS_INACTIVE: 'INACTIVE',
	STATUS_ACTIVE: 'ACTIVE',
	STATUS_CREATE: 'CREATE',
};

export default {
	STATUS_INACTIVE,
	STATUS_ACTIVE,
	STATUS_CREATE,
	ROLE_USER_ADMIN,
	ROLE_USER_SUPER_ADMIN,
	USER_STATUS_NAME,
};
