# name: Test CD

name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        id: ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22 # Agar default port (22) bo'lmasa, portni ko'rsating
          script: |
            cd ~/ecomm_api/
            git pull
            npm install
            pm2 restart 0

      - name: Notify Telegram on success
        if: success()
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Successfully. Server PROD"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Failed. Server PROD"
