# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      uses: mnival/ssh-config-action@v0.0.2
        with:
          host: ${{ secrets.SSH_BAR_HOST }}
          username: ${{ secrets.SSH_BAR_USER }}
          password: ${{ secrets.SSH_BAR_KEY }}
          key: ${{ secrets.SSH_KEY}}
          port: 22
          script:
              cd ~/ecomm_api/
              git pull
              npm install
              pm2 restart 0