name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Node versiyasi

      - name: Install dependencies
        run: npm install

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        id: ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            set -x
            cd ~/ecomm_api/ || { echo "Failed to change directory"; exit 1; }
            git config pull.rebase false || { echo "git config failed"; exit 1; }
            git stash || { echo "git stash failed"; exit 1; }
            git pull -X theirs || { echo "git pull failed"; exit 1; }
            git stash pop || { echo "git stash pop failed"; exit 1; }
            npm install || { echo "npm install failed"; exit 1; }
            npx sequelize-cli db:migrate || { echo "sequelize migrate failed"; exit 1; }
            pm2 restart 0 || { echo "pm2 restart failed"; exit 1; }
            set +x

      - name: Notify Telegram on success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Successfully. Server PROD"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Failed. Server PROD"
