name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # Node.js qo'llab-quvvatlanadigan versiyalar jadvalini https://nodejs.org/en/about/releases/ sahifasida ko'rishingiz mumkin

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Notify Telegram on push success
        if: github.event_name == 'push' && success()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_MESSAGE_ENCODED=$(echo $COMMIT_MESSAGE | jq -sRr @uri)
          COMMIT_AUTHOR_ENCODED=$(echo $COMMIT_AUTHOR | jq -sRr @uri)
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Push successful.%0ACommit: $COMMIT_MESSAGE_ENCODED%0AAuthor: $COMMIT_AUTHOR_ENCODED"

      - name: Notify Telegram on pull request success
        if: github.event_name == 'pull_request' && success()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          COMMIT_MESSAGE_ENCODED=$(echo $COMMIT_MESSAGE | jq -sRr @uri)
          COMMIT_AUTHOR_ENCODED=$(echo $COMMIT_AUTHOR | jq -sRr @uri)
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="Pull request successful.%0ACommit: $COMMIT_MESSAGE_ENCODED%0AAuthor: $COMMIT_AUTHOR_ENCODED"
